hacsoc/acm.case.edu

Gemfile.lock
app/controllers/acm.rb
app/views/acm/conference/2015.haml
app/views/acm/index.haml
config/speakers.yml
config/sponsors.yml

It's a start! Got LinkState 2015 pages up and connected. Lots of work to do on making it functional and content to add, but it looks like something.

Getting initial LinkState 2015 material up

---

README.md

Just updated README to mention 2.2.1 for local testing. Still need deploy information from @Aaronneyer. Further information expected Wednesday.

Change to mention 2.2.1, Creating Deploy information

---

app/views/acm/index.haml

Dealing with the HackCWRU site can happen later, but this at least gives us some connection between the sites.

Put a short piece on HackCWRU up and a link to the current HackCWRU site

---

app/views/acm/conference/2015.haml
app/views/acm/index.haml

Here's a section and a meta-statement about requesting attention from speakers. Suggestions for making some substance in this section?

Creating a Call-for-Speakers Section for Link-State 2015

---

Dockerfile
Gemfile
Gemfile.lock
unicorn.conf

Files needed for production on docker.case.edu.  Uses unicorn on port 80.

production files and changes

---

README.md

Quick and simple README update.

Added link to acm.case.edu and improved the getting-started instructions

---

app/views/acm/servers.haml

Fix the Quassal link

---

app/controllers/hackcwru.rb

fix formatting

---

app/views/acm/conference/2015.haml

Using *Padrino*'s feature for adding meta tags to a page, here are some card bits.
Edit: which of our Twitter accounts should this page/card be credited towards?

Taking a try at adding a Twitter Card

---

app/views/acm/conference/2015.haml

Having the date in the description and trying to get the image to work using a full link in the meta tag (still with programmatic retrieval of the path).

Improving the Link-State 2015 Twitter Card

---

app/views/acm/index.haml

@matthewbentley if you want a different email listed, let me know.

bentley is the admin now

---

app/views/acm/index.haml

Pushing through immediately to fix production bug.

Fix using markdown where it isn't appropriate

---

app/views/acm/conference/2015.haml

It's an iFrame. It sells tickets.

Create Register h2 and add EventBrite ticket ordering iFrame

---

app/views/acm/conference/2015.haml
config/speakers.yml

Hey yo, a first speaker!
This has been successfully tested locally.

Initial setup for speakers; Speaker information for Charlotte Chang

---

app/views/acm/conference/2015.haml
config/speakers.yml

Along with a hack to make the paragraph breaks work properly in this year's bios
The trick is to indent the next paragraphs another space.

Publish Brian Stack as a speaker

---

app/views/acm/conference/2015.haml
config/speakers.yml

Publish Eric Floehr as a speaker

---

app/views/acm/conference/2015.haml
config/speakers.yml

 Publish Charlotte Chang & Nicole Capuana as speakers 

---

app/views/acm/conference/2015.haml
config/speakers.yml

We will have an update later to publish names+bios, but we are initially publishing with this information.

Publish NASA Glenn's GVIS as speakers

---

app/views/acm/conference/2015.haml

Do these times look good relative to the schedule?

Give Exact Event Time

---

app/views/acm/conference/2015.haml
config/speakers.yml

Speaker names+bios from Herb. We can hope that the government doesn't shut down.

Post speaker names for NASA Glenn's GVIS

---

app/views/acm/conference/2015.haml

Swaps out call-for-speakers+sponsors for looking more like it's time to put on the conference.

Switch over to giving-a-conference mode

---

app/controllers/acm.rb
app/views/layouts/application.haml

- TIL you can interpolate ruby strings inside of haml interpolation

closes #103. remove -- from the title conditionally

---

app/views/acm/servers.haml

- maintainers updated for ACM and IRC
- declare minecraft as not running
- not sure about starbound, so it is unchanged

closes #87. update maintainers

---

app/controllers/acm.rb
app/views/acm/conference/code.haml

Comments on this are very much encouraged.  What I have here is adapted from [this](http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy) wiki page about anti-harassment policies (found that page from the PyCon [code of conduct](https://github.com/python/pycon-code-of-conduct/blob/master/code_of_conduct.md)).
Since the original is more targeted to anti-harassment topics, I tried to make this a bit more general sounding, while still including plenty of anti-harassment language, mostly so we could feel confident that this policy would clearly restrict behavior we've had in the past that was less than satisfactory.
Comments and suggestions very welcome.

Add initial code of conduct for LinkState.

---

app/app.rb
app/controllers/acm.rb
app/views/acm/conference/2016.haml
app/views/acm/conference/about.haml
app/views/acm/index.haml
config/speakers.yml
config/sponsors.yml

But it's better than nothing.  I think I covered all my bases.

Initial site for Link-State 2016.  Lots of TBD's.

---

app/controllers/acm.rb
app/views/acm/conference/2016.haml

@matthewbentley this ones' for you!

Add call for proposals for 2016.

---

app/controllers/acm.rb

Fix ACM link pointing to CFP.  Ruby is hard guys.

---

app/views/acm/conference/2016.haml

Also adds a slightly expanded intro paragraph and sets the time to be 7:00 AM - 5:00 PM (which we can change if necessary).

Add Facebook event and Eventbrite.

---

app/views/acm/conference/2016.haml
config/speakers.yml

A second update to the speaker list and schedule.

---

app/views/acm/conference/2016.haml
config/speakers.yml

A third update to the speaker list and schedule.

---

app/views/acm/conference/2016.haml

Fix lunch schedule for Lynn

---

config/speakers.yml

CSS Security -> Certified Security Solutions

---

app/views/acm/conference/2017.haml

modified  2016 website but updated for 2017.

LINKSTATE 2017

---

app/views/acm/index.haml

Changed exec. Also included links to link state 2017 and referenced  the next HACKWRU instead ofHACKCWRU 2016.

changes to index

---

app/controllers/acm.rb

-made changes required to display link state 2017 
- updated IEE president info

Link State 2017 changes

---

app/views/acm/conference/2017.haml

-Had a slight syntax error in line 88. Removed said error.   
-Added link to actual face book event. 
- Change description to reflect actual date of event .

Small Errors

---

Gemfile
Gemfile.lock

Fixes docker build so we can deploy again

Update to ruby 2.4.2
